stages:
  visualize_data:
    cmd: py src/data_visualization.py
    deps:
      - data/raw/bank-additional-full.csv
    outs:
      - docs/figures/
  test_data_quality:
    cmd: pytest --html=docs/test_results/test_results.html --self-contained-html  test/test_data_quality.py
    deps:
      - test/test_data_quality.py
      - data/raw/bank-additional-full.csv
    outs:
      - docs/test_results/test_results.html
  test_data_gx:
    cmd: pytest --html=docs/test_results/test_results-gx.html --self-contained-html test/test_data_gx.py
    deps:
      - test/test_data_quality.py
      - data/raw/bank-additional-full.csv
    outs:
      - docs/test_results/test_results-gx.html